version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: bot-stock-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bot_stock
    ports:
      - "5432:5432"
    volumes:
      - bot_stock_postgres_data:/var/lib/postgresql/data

  app:
    container_name: bot-stock-app
    build: .
    restart: unless-stopped
    depends_on:
      - postgres
    env_file:
      - .env
    command: sh -c "npm run prestart && npm run start"
    ports:
      - "3003:3000"

volumes:
  bot_stock_postgres_data:
